const ACHIVEMENT_DATA = [
  {
    "id": "achive1",
    "icon": {"x": 12, "y": 3},
    "thumnail": {"x": 1, "y": 0},
    "title": "持ち物ゲット",
    "description": "持ち物を開こう。",
    "detail": "インベントリを開く。",
    "gold": "10",
  },{
    "id": "achive2",
    "icon": {"x": 8, "y": 1},
    "thumnail": {"x": 2, "y": 0},
    "title": "木を手に入れよう",
    "description": "木のブロックが出てくるまで衝撃を与えよう。",
    "detail": "落ちている原木を拾う。",
    "gold": "10",
  },{
    "id": "achive3",
    "icon": {"x": 11, "y": 0},
    "thumnail": {"x": 3, "y": 0},
    "title": "土台作り",
    "description": "板材 4 ブロックを材料に、作業台を作ろう。",
    "detail": "インベントリのクラフトから作業台を作る。",
    "gold": "10",
  },{
    "id": "achive4",
    "icon": {"x": 5, "y": 4},
    "thumnail": {"x": 4, "y": 0},
    "title": "いざ採掘！",
    "description": "板材と棒を材料に、ツルハシを作ろう。",
    "detail": "作業台でいずれかのツルハシを作る。",
    "gold": "10",
  },{
    "id": "achive5",
    "icon": {"x": 13, "y": 1},
    "thumnail": {"x": 5, "y": 0},
    "title": "ホットトピック",
    "description": "8 つの丸石ブロックを材料に、かまどを作ろう。",
    "detail": "作業台で丸石を8つ使い、かまどを作る。",
    "gold": "15",
  },{
    "id": "achive6",
    "icon": {"x": 1, "y": 0},
    "thumnail": {"x": 0, "y": 1},
    "title": "メタルに決めろ",
    "description": "鉄インゴットを精錬しよう。",
    "detail": "かまどから鉄インゴットを取り出す。",
    "gold": "15",
  },{
    "id": "achive7",
    "icon": {"x": 4, "y": 4},
    "thumnail": {"x": 1, "y": 1},
    "title": "いざ農業！",
    "description": "クワを作ろう。",
    "detail": "作業台からクワを取り出す。",
    "gold": "10",
  },{
    "id": "achive8",
    "icon": {"x": 7, "y": 0},
    "thumnail": {"x": 2, "y": 1},
    "title": "パンを焼く",
    "description": "小麦からパンを作ろう。",
    "detail": "作業台からパンを取り出す。",
    "gold": "15",
  },{
    "id": "achive9",
    "icon": {"x": 0, "y": 4},
    "thumnail": {"x": 3, "y": 1},
    "title": "絵に描いた〇〇〇",
    "description": "次の材料を使ってケーキを焼こう: 小麦、砂糖、ミルク、卵。",
    "detail": "作業台でケーキを作る。",
    "gold": "30",
  },{
    "id": "achive10",
    "icon": {"x": 7, "y": 1},
    "thumnail": {"x": 4, "y": 1},
    "title": "アップグレード",
    "description": "より質の高いツルハシを作ろう	。",
    "detail": "作業台から木のツルハシ以外のツルハシを作る。",
    "gold": "15",
  },{
    "id": "achive11",
    "icon": {"x": 21, "y": 0},
    "thumnail": {"x": 5, "y": 1},
    "title": "美味しい魚",
    "description": "魚を捕まえて、料理しよう！",
    "detail": "かまどから焼き鱈または焼き鮭を取り出す。",
    "gold": "15",
  },{
    "id": "achive12",
    "icon": {"x": 9, "y": 2},
    "thumnail": {"x": 0, "y": 2},
    "title": "世界のトロッコから",
    "description": "トロッコに乗って、スタート地点から一定方向に 500 m 以上進もう。",
    "detail": "トロッコに乗って、スタート地点から500メートル進む。",
    "gold": "40",
  },{
    "id": "achive13",
    "icon": {"x": 6, "y": 4},
    "thumnail": {"x": 1, "y": 2},
    "title": "いざ突撃！",
    "description": "板材と棒を材料に、剣を作ろう。",
    "detail": "作業台から剣を取り出す。",
    "gold": "10",
  },{
    "id": "achive14",
    "icon": {"x": 7, "y": 2},
    "thumnail": {"x": 2, "y": 2},
    "title": "モンスター退治",
    "description": "モンスターを攻撃して倒そう。",
    "detail": "敵対モブ、またはエンダーマン、ゾンビ化ピグリン、スパイダー、ケイブスパイダーを倒す。",
    "gold": "15",
  },{
    "id": "achive15",
    "icon": {"x": 19, "y": 0},
    "thumnail": {"x": 3, "y": 2},
    "title": "牛転がし",
    "description": "革を手に入れよう。",
    "detail": "落ちている革を拾う。",
    "gold": "15",
  },{
    "id": "achive16",
    "icon": {"x": 11, "y": 4},
    "thumnail": {"x": 4, "y": 2},
    "title": "ブタさんの飛ぶ頃に",
    "description": "鞍を使って豚に乗り、乗っている最中に豚に落下ダメージを与えよう。",
    "detail": "鞍を使ってブタに乗り、乗ったままブタが落下ダメージを受ける。",
    "gold": "40",
  },{
    "id": "achive17",
    "icon": {"x": 2, "y": 3},
    "thumnail": {"x": 5, "y": 2},
    "title": "スナイパー対決",
    "description": "50 m 離れたところから矢を放ってスケルトンを倒そう",
    "detail": "50ブロック以上離れたところから矢を使い、スケルトンまたはウィザースケルトンを倒す。",
    "gold": "30",
  },{
    "id": "achive18",
    "icon": {"x": 22, "y": 0},
    "thumnail": {"x": 0, "y": 3},
    "title": "ダイヤモンド！",
    "description": "鉄の道具を使ってダイヤモンドをゲットしよう。",
    "detail": "落ちているダイヤモンドを拾う。",
    "gold": "20",
  },{
    "id": "achive19",
    "icon": {"x": 18, "y": 1},
    "thumnail": {"x": 1, "y": 3},
    "title": "ネザーへ",
    "description": "ネザー ポータルを作ろう。",
    "detail": "ネザー ポータルを起動させる。",
    "gold": "30",
  },{
    "id": "achive20",
    "icon": {"x": 21, "y": 2},
    "thumnail": {"x": 2, "y": 3},
    "title": "仕返し",
    "description": "火の玉でガストを倒そう。",
    "detail": "ガストの火の玉をを跳ね返して倒す。",
    "gold": "30",
  },{
    "id": "achive21",
    "icon": {"x": 17, "y": 1},
    "thumnail": {"x": 3, "y": 3},
    "title": "炎の中へ",
    "description": "ロッドからブレイズを解放しよう。",
    "detail": "落ちているブレイズロッドを拾う。",
    "gold": "20",
  },{
    "id": "achive22",
    "icon": {"x": 3, "y": 2},
    "thumnail": {"x": 4, "y": 3},
    "title": "町の薬屋さん",
    "description": "ポーションを調合しよう。",
    "detail": "醸造台からポーションを取り出す。",
    "gold": "15",
  },{
    "id": "achive23",
    "icon": {"x": 22, "y": 3},
    "thumnail": {"x": 5, "y": 3},
    "title": "おしまい？",
    "description": "エンドポータルに入ろう",
    "detail": "エンドポータルに入る。",
    "gold": "20",
  },{
    "id": "achive24",
    "icon": {"x": 19, "y": 3},
    "thumnail": {"x": 0, "y": 4},
    "title": "おしまい。",
    "description": "エンダー ドラゴンを倒そう",
    "detail": "エンダードラゴンを倒した後、帰還ポータルに入る。",
    "gold": "40",
  },{
    "id": "achive25",
    "icon": {"x": 2, "y": 1},
    "thumnail": {"x": 1, "y": 4},
    "title": "エンチャンター",
    "description": "エンチャントテーブルを作ろう。",
    "detail": "作業台からエンチャントテーブルを取り出す。",
    "gold": "20",
  },{
    "id": "achive26",
    "icon": {"x": 11, "y": 2},
    "thumnail": {"x": 2, "y": 4},
    "title": "強力な破壊力",
    "description": "一叩きでハート 9 つ分のダメージを与えよう。",
    "detail": "全てのモブでダメージを与えれば達成する。",
    "gold": "30",
  },{
    "id": "achive27",
    "icon": {"x": 1, "y": 2},
    "thumnail": {"x": 3, "y": 4},
    "title": "司書",
    "description": "本棚を作ってエンチャントテーブルを強化しよう。",
    "detail": "作業台から本棚を取り出す。",
    "gold": "20",
  },{
    "id": "achive28",
    "icon": {"x": 2, "y": 0},
    "thumnail": {"x": 4, "y": 4},
    "title": "冒険の時間",
    "description": "17種のバイオームを見つけよう	。",
    "detail": "17種類のバイオームに訪れる。",
    "gold": "40",
  },{
    "id": "achive29",
    "icon": {"x": 16, "y": 3},
    "thumnail": {"x": 5, "y": 4},
    "title": "はじまり？",
    "description": "ウィザーを出現させよう",
    "detail": "ソウルサンド4つとウィザースケルトンの頭3つを配置して、ウィザーを召喚する。",
    "gold": "20",
  },{
    "id": "achive30",
    "icon": {"x": 15, "y": 3},
    "thumnail": {"x": 0, "y": 5},
    "title": "はじまり。",
    "description": "ウィザーを倒そう。",
    "detail": "ウィザーを倒した後にドロップするネザースターを拾う。",
    "gold": "40",
  },{
    "id": "achive31",
    "icon": {"x": 8, "y": 0},
    "thumnail": {"x": 1, "y": 5},
    "title": "ビーコン使い",
    "description": "ビーコンを作ってフルパワーにしよう",
    "detail": "鉱石ブロックをピラミッド型に配置し、ビーコンに電力が供給された時に20×20×14の範囲内にいる。",
    "gold": "60",
  },{
    "id": "achive32",
    "icon": {"x": 20, "y": 2},
    "thumnail": {"x": 2, "y": 5},
    "title": "再繁殖",
    "description": "小麦を与えて牛を 2 頭繁殖させよう。",
    "detail": "2匹のウシかムーシュルームを繁殖させる。",
    "gold": "15",
  },{
    "id": "achive33",
    "icon": {"x": 23, "y": 0},
    "thumnail": {"x": 3, "y": 5},
    "title": "ダイヤモンドをあなたに！",
    "description": "他のプレイヤーにダイヤモンドを投げよう。",
    "detail": "ダイヤモンドをドロップして、他のプレイヤーかモブに拾わせる。",
    "gold": "15",
  },{
    "id": "achive34",
    "icon": {"x": 13, "y": 2},
    "thumnail": {"x": 4, "y": 5},
    "title": "圧倒的な力",
    "description": "エンチャントされたリンゴを食べよう",
    "detail": "エンチャントされたリンゴを食べる。",
    "gold": "30",
  },{
    "id": "achive35",
    "icon": {"x": 6, "y": 2},
    "thumnail": {"x": 5, "y": 5},
    "title": "ツールスミス",
    "description": "すべての道具を 1 タイプずつ作ろう。",
    "detail": "道具類(ツルハシ、シャベル、斧、クワ）を全種類1つずつ作る。",
    "gold": "15",
  },{
    "id": "achive36",
    "icon": {"x": 0, "y": 1},
    "thumnail": {"x": 0, "y": 6},
    "title": "発射はこれで",
    "description": "発射装置を作ろう。",
    "detail": "作業台でディスペンサーを作る。",
    "gold": "20",
  },{
    "id": "achive37",
    "icon": {"x": 22, "y": 1},
    "thumnail": {"x": 1, "y": 6},
    "title": "群れのリーダー",
    "description": "5 匹のオオカミと友達になろう。",
    "detail": "野生のオオカミを5匹手懐ける必要がある。",
    "gold": "20",
  },{
    "id": "achive38",
    "icon": {"x": 15, "y": 2},
    "thumnail": {"x": 2, "y": 6},
    "title": "ポーク チョップ",
    "description": "豚肉を焼いて食べよう。",
    "detail": "生の豚肉を精錬し、焼き豚を食べる。",
    "gold": "10",
  },{
    "id": "achive39",
    "icon": {"x": 14, "y": 2},
    "thumnail": {"x": 3, "y": 6},
    "title": "暇つぶし",
    "description": "100 日間プレイしよう。",
    "detail": "ゲーム内時間で100日プレイする。",
    "gold": "20",
  },{
    "id": "achive40",
    "icon": {"x": 23, "y": 3},
    "thumnail": {"x": 4, "y": 6},
    "title": "商売人",
    "description": "村人との取引で、30 個のエメラルドを手に入れるか、支払おう。",
    "detail": "-",
    "gold": "30",
  },{
    "id": "achive41",
    "icon": {"x": 16, "y": 2},
    "thumnail": {"x": 5, "y": 6},
    "title": "鉢植えガーデナー",
    "description": "植木鉢を作って設置しよう。",
    "detail": "-",
    "gold": "15",
  },{
    "id": "achive42",
    "icon": {"x": 21, "y": 1},
    "thumnail": {"x": 0, "y": 7},
    "title": "看板を作ろう!",
    "description": "樫の看板を作って設置しよう",
    "detail": "-",
    "gold": "15",
  },{
    "id": "achive43",
    "icon": {"x": 19, "y": 1},
    "thumnail": {"x": 1, "y": 7},
    "title": "強靭なお腹",
    "description": "腐った肉で飢えをしのごう。",
    "detail": "空腹ゲージが0の状態で腐った肉を食べる。",
    "gold": "20",
  },{
    "id": "achive44",
    "icon": {"x": 12, "y": 1},
    "thumnail": {"x": 2, "y": 7},
    "title": "毛刈り日和",
    "description": "ハサミを使って羊の羊毛を刈ろう。",
    "detail": "-",
    "gold": "15",
  },{
    "id": "achive45",
    "icon": {"x": 18, "y": 2},
    "thumnail": {"x": 3, "y": 7},
    "title": "虹色コレクション",
    "description": "全 16 色の羊毛を集めよう。",
    "detail": "羊毛は全色同時にインベントリに存在していなくてもよいが、プレイヤーは少なくとも一度は拾ったことがある必要がある。",
    "gold": "30",
  },{
    "id": "achive46",
    "icon": {"x": 7, "y": 3},
    "thumnail": {"x": 4, "y": 7},
    "title": "熱に負けない",
    "description": "耐火効果がある間に溶岩の中を泳ごう。",
    "detail": "-",
    "gold": "20",
  },{
    "id": "achive47",
    "icon": {"x": 18, "y": 0},
    "thumnail": {"x": 5, "y": 7},
    "title": "丸石がいっぱい",
    "description": "丸石を 1,728個集めてチェストに入れましょう。",
    "detail": "丸石を1728個採掘し、チェストに1728個（＝27スタック）の丸石を入れる。",
    "gold": "20",
  },{
    "id": "achive48",
    "icon": {"x": 19, "y": 2},
    "thumnail": {"x": 0, "y": 8},
    "title": "再生可能エネルギー",
    "description": "木炭で木の幹を精錬し、もっと木炭を作ろう。",
    "detail": "木炭を燃料として原木を製錬する。",
    "gold": "10",
  },{
    "id": "achive49",
    "icon": {"x": 12, "y": 0},
    "thumnail": {"x": 1, "y": 8},
    "title": "ボディー ガード",
    "description": "アイアン ゴーレムを作ろう。",
    "detail": "アイアン ゴーレムを作る。",
    "gold": "20",
  },{
    "id": "achive50",
    "icon": {"x": 20, "y": 1},
    "thumnail": {"x": 2, "y": 8},
    "title": "鉄の男",
    "description": "鉄の防具を全身に装備しよう。",
    "detail": "鉄製の防具をインベントリに入れる。",
    "gold": "15",
  },{
    "id": "achive51",
    "icon": {"x": 14, "y": 4},
    "thumnail": {"x": 3, "y": 8},
    "title": "ゾンビの医者",
    "description": "ゾンビ村人を治療しよう。",
    "detail": "弱体化のステータス効果が付与されている村人ゾンビに金のリンゴを与え、村人に戻す。",
    "gold": "40",
  },{
    "id": "achive52",
    "icon": {"x": 2, "y": 2},
    "thumnail": {"x": 4, "y": 8},
    "title": "ライオン ハンター",
    "description": "ヤマネコをなつかれよう。",
    "detail": "野生状態のヤマネコに生鮭または生鱈を与え、信頼を与える。",
    "gold": "15",
  },{
    "id": "achive53",
    "icon": {"x": 3, "y": 0},
    "thumnail": {"x": 5, "y": 8},
    "title": "弓兵",
    "description": "クリーパーを矢で倒そう。",
    "detail": "—",
    "gold": "10",
  },{
    "id": "achive54",
    "icon": {"x": 3, "y": 4},
    "thumnail": {"x": 0, "y": 9},
    "title": "絞り染め衣装",
    "description": "大釜を使って革の防具の4つの異なる装備を染めよう。",
    "detail": "-",
    "gold": "15",
  },{
    "id": "achive55",
    "icon": {"x": 0, "y": 5},
    "thumnail": {"x": 1, "y": 9},
    "title": "トランポリン",
    "description": "スライムブロックから30ブロック以上跳ね上がろう。",
    "detail": "—",
    "gold": "15",
  },{
    "id": "achive56",
    "icon": {"x": 14, "y": 0},
    "thumnail": {"x": 2, "y": 9},
    "title": "カモフラージュ",
    "description": "ある種類のモブの頭部を装備して、そのモブを倒そう。",
    "detail": "モブの頭を装備し、装備しているモブの頭の種類と同じモブを倒す。",
    "gold": "30",
  },{
    "id": "achive57",
    "icon": {"x": 20, "y": 4},
    "thumnail": {"x": 3, "y": 9},
    "title": "地図の間",
    "description": "完全に探索が完了した隣接する地図を、9 つの 3 × 3 の正方形フレームに入れよう",
    "detail": "額縁は床ではなく壁に設置されていなければならない。",
    "gold": "40",
  },{
    "id": "achive58",
    "icon": {"x": 6, "y": 1},
    "thumnail": {"x": 4, "y": 9},
    "title": "貨物駅",
    "description": "ホッパーを使って、アイテムをチェスト付きトロッコからチェストへと移動しよう。",
    "detail": "—",
    "gold": "15",
  },{
    "id": "achive59",
    "icon": {"x": 1, "y": 3},
    "thumnail": {"x": 5, "y": 9},
    "title": "何でも溶かしてしまおう！",
    "description": "3 つのホッパーを使って、3 つのチェストをかまどにつなげよう。",
    "detail": "ホッパーが3つあるかまどに接続された3つのチェストの範囲内に居なければならない。",
    "gold": "15",
  },{
    "id": "achive60",
    "icon": {"x": 14, "y": 3},
    "thumnail": {"x": 0, "y": 10},
    "title": "やられたらやり返せ",
    "description": "スプラッシュ ポーションでウィッチに毒を与えよう。",
    "detail": "毒のスプラッシュポーションをウィッチに向かって投げる。",
    "gold": "20",
  },{
    "id": "achive61",
    "icon": {"x": 16, "y": 1},
    "thumnail": {"x": 1, "y": 10},
    "title": "発端",
    "description": "ピストンで別のピストンを押し、それから元のピストンをそのピストンで引こう。",
    "detail": "—",
    "gold": "20",
  },{
    "id": "achive62",
    "icon": {"x": 0, "y": 3},
    "thumnail": {"x": 2, "y": 10},
    "title": "はいどうどう",
    "description": "馬を手なずけよう。",
    "detail": "—",
    "gold": "20",
  },{
    "id": "achive63",
    "icon": {"x": 4, "y": 0},
    "thumnail": {"x": 3, "y": 10},
    "title": "人工的選択",
    "description": "馬とロバからラバを繁殖させよう。",
    "detail": "—",
    "gold": "30",
  },{
    "id": "achive64",
    "icon": {"x": 5, "y": 1},
    "thumnail": {"x": 4, "y": 10},
    "title": "スキン ダイバー",
    "description": "水中に 2 分間潜ろう。",
    "detail": "水中呼吸のポーションを使用した状態で水中に飛び込み、コンジットを起動したり、水中のマグマブロックの上でスニークしたりする。",
    "gold": "20",
  },{
    "id": "achive65",
    "icon": {"x": 17, "y": 2},
    "thumnail": {"x": 5, "y": 10},
    "title": "ウサギの季節",
    "description": "ウサギの肉を調理して食べよう。",
    "detail": "生の兎肉を精錬し、焼き兎肉を食べる。",
    "gold": "15",
  },{
    "id": "achive66",
    "icon": {"x": 18, "y": 3},
    "thumnail": {"x": 0, "y": 11},
    "title": "地中の果て",
    "description": "エルダー ガーディアンを倒そう",
    "detail": "—",
    "gold": "30",
  },{
    "id": "achive67",
    "icon": {"x": 1, "y": 1},
    "thumnail": {"x": 1, "y": 11},
    "title": "乾燥魔法",
    "description": "スポンジをかまどで乾かそう",
    "detail": "濡れたスポンジをかまどで精錬し、かまどからスポンジを取り出す。",
    "gold": "15",
  },{
    "id": "achive68",
    "icon": {"x": 9, "y": 3},
    "thumnail": {"x": 2, "y": 11},
    "title": "スーパー燃料",
    "description": "溶岩をかまどの燃料に使おう",
    "detail": "—",
    "gold": "20",
  },{
    "id": "achive69",
    "icon": {"x": 13, "y": 4},
    "thumnail": {"x": 3, "y": 11},
    "title": "お口が臭いです",
    "description": "ガラスビンにドラゴンブレスを集めよう",
    "detail": "ドラゴンブレスをインベントリに入れる。",
    "gold": "30",
  },{
    "id": "achive70",
    "icon": {"x": 10, "y": 0},
    "thumnail": {"x": 4, "y": 11},
    "title": "いざテレポート",
    "description": "エンダーパールを 1 回投げるだけで 100 メートル以上テレポートしよう",
    "detail": "エンダーパールを任意の方向に100ブロック投げる。",
    "gold": "20",
  },{
    "id": "achive71",
    "icon": {"x": 21, "y": 3},
    "thumnail": {"x": 5, "y": 11},
    "title": "おしまい...再び...",
    "description": "エンダー ドラゴンを再出現させよう",
    "detail": "—",
    "gold": "30",
  },{
    "id": "achive72",
    "icon": {"x": 10, "y": 1},
    "thumnail": {"x": 0, "y": 12},
    "title": "上からのいい眺め",
    "description": "シュルカーの攻撃で 50 ブロックの高さに上昇しよう",
    "detail": "—",
    "gold": "20",
  },{
    "id": "achive73",
    "icon": {"x": 11, "y": 3},
    "thumnail": {"x": 1, "y": 12},
    "title": "超音速",
    "description": "エリトラを使って 40 m/s 以上の速度で 1 × 1 の隙間を通り過ぎよう。",
    "detail": "—",
    "gold": "30",
  },{
    "id": "achive74",
    "icon": {"x": 9, "y": 4},
    "thumnail": {"x": 2, "y": 12},
    "title": "トレジャー ハンター",
    "description": "製図家の村人から地図を入手して、その地図で見つかった建物に入ろう。",
    "detail": "購入した地図を利き手（ホットバー）に持った状態で、表示されている構造物に訪れる。",
    "gold": "40",
  },{
    "id": "achive75",
    "icon": {"x": 10, "y": 2},
    "thumnail": {"x": 3, "y": 12},
    "title": "組織的な魔術師",
    "description": "金床を使ってシュルカーボックスに名前を付けよう",
    "detail": "—",
    "gold": "30",
  },{
    "id": "achive76",
    "icon": {"x": 17, "y": 0},
    "thumnail": {"x": 4, "y": 12},
    "title": "九死に一生",
    "description": "不死のトーテムを使って、死をまのがれよう",
    "detail": "不死のトーテムを持ったまま死ぬ。",
    "gold": "30",
  },{
    "id": "achive77",
    "icon": {"x": 4, "y": 1},
    "thumnail": {"x": 5, "y": 12},
    "title": "気分が悪い",
    "description": "エヴォーカーを倒そう",
    "detail": "—",
    "gold": "30",
  },{
    "id": "achive78",
    "icon": {"x": 0, "y": 2},
    "thumnail": {"x": 0, "y": 13},
    "title": "ありの～ままの～!",
    "description": "氷上歩行のブーツを装備して、海に張った氷の上を 1 ブロック歩こう。",
    "detail": "—",
    "gold": "20",
  },{
    "id": "achive79",
    "icon": {"x": 6, "y": 3},
    "thumnail": {"x": 1, "y": 13},
    "title": "やりたいことをやった",
    "description": "5 頭以上のラマを連れたキャラバンを率いよう",
    "detail": "—",
    "gold": "20",
  },{
    "id": "achive80",
    "icon": {"x": 17, "y": 4},
    "thumnail": {"x": 2, "y": 13},
    "title": "アトランティス？",
    "description": "海底遺跡を見つけよう",
    "detail": "—",
    "gold": "20",
  },{
    "id": "achive81",
    "icon": {"x": 22, "y": 4},
    "thumnail": {"x": 3, "y": 13},
    "title": "７つの海の航海",
    "description": "全種類の海洋バイオームを訪れよう",
    "detail": "全ての海洋バイオームを訪れる。",
    "gold": "40",
  },{
    "id": "achive82",
    "icon": {"x": 18, "y": 4},
    "thumnail": {"x": 4, "y": 13},
    "title": "漂流者",
    "description": "乾燥昆布だけを食べて、ゲーム内時間で３日過ごそう",
    "detail": "まず乾燥した昆布を食べ、その後ゲーム内時間で3日間乾燥した昆布以外は食べない。",
    "gold": "20",
  },{
    "id": "achive83",
    "icon": {"x": 15, "y": 4},
    "thumnail": {"x": 5, "y": 13},
    "title": "アホイ！",
    "description": "難破船を見つけよう",
    "detail": "—",
    "gold": "20",
  },{
    "id": "achive84",
    "icon": {"x": 19, "y": 4},
    "thumnail": {"x": 0, "y": 14},
    "title": "我こそ海洋生物学者",
    "description": "バケツに魚を入れよう",
    "detail": "魚のモブに対して空のバケツを使用し捕獲する。",
    "gold": "20",
  },{
    "id": "achive85",
    "icon": {"x": 21, "y": 4},
    "thumnail": {"x": 1, "y": 14},
    "title": "自分だけのお宝!",
    "description": "隠し財宝を掘り出そう",
    "detail": "埋もれた宝のチェストを開く。",
    "gold": "30",
  },{
    "id": "achive86",
    "icon": {"x": 23, "y": 4},
    "thumnail": {"x": 2, "y": 14},
    "title": "海の藻屑",
    "description": "水中で１日過ごそう。",
    "detail": "水中で20分間過ごす。",
    "gold": "30",
  },{
    "id": "achive87",
    "icon": {"x": 16, "y": 4},
    "thumnail": {"x": 3, "y": 14},
    "title": "代替燃料",
    "description": "かまどの燃料に昆布ブロックを使おう",
    "detail": "乾燥した昆布ブロックをかまどの燃料スロットに入れる。",
    "gold": "20",
  },{
    "id": "achive88",
    "icon": {"x": 1, "y": 5},
    "thumnail": {"x": 4, "y": 14},
    "title": "バレルロール",
    "description": "激流を使って加速しよう",
    "detail": "激流のエンチャントが付与されたトライデントを持って、投げる。",
    "gold": "30",
  },{
    "id": "achive89",
    "icon": {"x": 4, "y": 5},
    "thumnail": {"x": 5, "y": 14},
    "title": "シーピクルスが１つ、２つ、３つ、４つ…",
    "description": "４つのシーピクルスをまとめて置こう",
    "detail": "—",
    "gold": "20",
  },{
    "id": "achive90",
    "icon": {"x": 2, "y": 5},
    "thumnail": {"x": 0, "y": 15},
    "title": "エコーロケーション",
    "description": "イルカに魚をあげて、宝の場所まで案内してもらおう",
    "detail": "イルカに生鮭または生鱈を与え、海底遺跡や難破船まで案内してもらう。",
    "gold": "20",
  },{
    "id": "achive91",
    "icon": {"x": 3, "y": 5},
    "thumnail": {"x": 1, "y": 15},
    "title": "モスケンの渦潮",
    "description": "コンジットを起動しよう",
    "detail": "プリズマリン・シーランタンの構造物にコンジットを設置して起動する。",
    "gold": "50",
  },{
    "id": "achive92",
    "icon": {"x": 6, "y": 5},
    "thumnail": {"x": 2, "y": 15},
    "title": "世界の頂点",
    "description": "限界の高さまで足場を置こう。",
    "detail": "ワールドの高度限界まで足場を設置する。",
    "gold": "20",
  },{
    "id": "achive93",
    "icon": {"x": 7, "y": 5},
    "thumnail": {"x": 3, "y": 15},
    "title": "どこに行ってたの？",
    "description": "朝、手なずけたネコからプレゼントをもらおう。",
    "detail": "プレゼントは地面から拾う必要がある。",
    "gold": "20",
  },{
    "id": "achive94",
    "icon": {"x": 8, "y": 5},
    "thumnail": {"x": 4, "y": 15},
    "title": "動物学者",
    "description": "２匹のパンダに竹をあげよう。",
    "detail": "—",
    "gold": "40",
  },{
    "id": "achive95",
    "icon": {"x": 5, "y": 5},
    "thumnail": {"x": 5, "y": 15},
    "title": "どこかで見たロゴ",
    "description": "エンチャントされたリンゴのステンシルを使って旗を作ろう",
    "detail": "エンチャントされたリンゴを使って旗を作る。",
    "gold": "20",
  },{
    "id": "achive96",
    "icon": {"x": 12, "y": 5},
    "thumnail": {"x": 0, "y": 16},
    "title": "ネコまみれ",
    "description": "２０匹の野生ネコと仲良くなろう",
    "detail": "村で見つけた20匹の野良状態のネコを飼いならす。",
    "gold": "20",
  },{
    "id": "achive97",
    "icon": {"x": 19, "y": 5},
    "thumnail": {"x": 1, "y": 16},
    "title": "怪物を倒せ！",
    "description": "ラヴェジャーを倒そう",
    "detail": "—",
    "gold": "30",
  },{
    "id": "achive98",
    "icon": {"x": 16, "y": 5},
    "thumnail": {"x": 2, "y": 16},
    "title": "安く買って高く売る",
    "description": "可能な範囲で最善の価格で取引しよう",
    "detail": "エメラルド1個分、または村の英雄のステータス効果が付与されている際に、何かを購入する。",
    "gold": "50",
  },{
    "id": "achive99",
    "icon": {"x": 17, "y": 5},
    "thumnail": {"x": 3, "y": 16},
    "title": "エンチャント解除",
    "description": "砥石を使って、エンチャントされたアイテムから経験値を手に入れよう",
    "detail": "—",
    "gold": "20",
  },{
    "id": "achive100",
    "icon": {"x": 21, "y": 5},
    "thumnail": {"x": 4, "y": 16},
    "title": "こちらは攻撃されている！",
    "description": "略奪者の襲撃を起こそう",
    "detail": "不吉な予感の効果が付与された状態で村を訪れる。",
    "gold": "20",
  },{
    "id": "achive101",
    "icon": {"x": 20, "y": 5},
    "thumnail": {"x": 5, "y": 16},
    "title": "警鐘を鳴らせ！",
    "description": "村の鐘で敵襲を知らせよう",
    "detail": "—",
    "gold": "20",
  },{
    "id": "achive102",
    "icon": {"x": 18, "y": 5},
    "thumnail": {"x": 0, "y": 17},
    "title": "嫌な予感がする",
    "description": "略奪者のリーダーを倒そう",
    "detail": "—",
    "gold": "20",
  },{
    "id": "achive103",
    "icon": {"x": 22, "y": 5},
    "thumnail": {"x": 1, "y": 17},
    "title": "取引の達人",
    "description": "エメラルドを 1,000 個取引しよう",
    "detail": "村人との取引でエメラルドを1,000個入手する。",
    "gold": "30",
  },{
    "id": "achive104",
    "icon": {"x": 23, "y": 5},
    "thumnail": {"x": 2, "y": 17},
    "title": "シチューの時間",
    "description": "誰かに怪しげなシチューをあげよう。",
    "detail": "—",
    "gold": "20",
  },{
    "id": "achive105",
    "icon": {"x": 0, "y": 6},
    "thumnail": {"x": 3, "y": 17},
    "title": "ハチをお迎え",
    "description": "焚き火でハチを怒らせないようにしながら、ビンを使って養蜂箱からハチミツを集めよう。",
    "detail": "焚き火を利用してハチを怒らせずにガラス瓶を使い、ハチミツ入りの瓶を手に入れる。",
    "gold": "15",
  },{
    "id": "achive106",
    "icon": {"x": 2, "y": 6},
    "thumnail": {"x": 4, "y": 17},
    "title": "ハチのお引越し",
    "description": "シルクタッチを使って、3 匹のハチが入った養蜂箱を別の場所へ移そう。",
    "detail": "3匹のハチが中に入っているミツバチの巣をインベントリに入れる。",
    "gold": "30",
  },{
    "id": "achive107",
    "icon": {"x": 1, "y": 6},
    "thumnail": {"x": 5, "y": 17},
    "title": "はちみつの甘さに魅せられて",
    "description": "ハチミツブロックに飛び降りて、落下を遅くしよう。",
    "detail": "横からハチミツブロックに飛び込み、落下を阻止する。",
    "gold": "30",
  },{
    "id": "achive108",
    "icon": {"x": 3, "y": 6},
    "thumnail": {"x": 0, "y": 18},
    "title": "ブルズアイ",
    "description": "的ブロックの的の中心を打つ",
    "detail": "水平方向に30メートル以上離れた場所から的の中心に発射物を当てる。",
    "gold": "15",
  },{
    "id": "achive109",
    "icon": {"x": 4, "y": 6},
    "thumnail": {"x": 2, "y": 18},
    "title": "がれきのカバー",
    "description": "ネテライトの防具一式を装備する",
    "detail": "ネザライト製の防具をインベントリに持つ。",
    "gold": "50",
  },{
    "id": "achive110",
    "icon": {"x": 6, "y": 6},
    "thumnail": {"x": 1, "y": 18},
    "title": "わーキレイ!",
    "description": "金を使ってピグリンの気をそらす",
    "detail": "敵対状態のピグリンに鐘・金の原石ブロック・時計・深層金鉱石・エンチャントされたリンゴ・きらめくブラックストーン・輝くスイカ・金ブロック・金インゴット・金鉱石・金のリンゴ・金の斧・金のブーツ・金のニンジン・金のチェストプレート・金のヘルメット・金のクワ・金の馬鎧・金のレギンス・金のツルハシ・金のシャベル・金の剣・感圧版 (軽)・ネザー金鉱石・パワードレール・金の原石の26種類のいずれかを与える。",
    "gold": "30",
  },{
    "id": "achive111",
    "icon": {"x": 5, "y": 6},
    "thumnail": {"x": 3, "y": 18},
    "title": "ホットな観光地",
    "description": "全てのネザーバイオームを訪れる",
    "detail": "ネザーのバイオーム全5種（ネザーの荒地、ソウルサンドの谷、真紅の森、歪んだ森、玄武岩の三角州）を訪れる。",
    "gold": "30",
  },{
    "id": "achive112",
    "icon": {"x": 0, "y": 0},
    "thumnail": {"x": 5, "y": 18},
    "title": "ヤギが浮くならなんでもあり",
    "description": "ヤギとボートに乗って浮く",
    "detail": "ヤギと一緒にボートに乗る。",
    "gold": "20",
  },{
    "id": "achive113",
    "icon": {"x": 0, "y": 0},
    "thumnail": {"x": 4, "y": 18},
    "title": "磨きあり、磨きなし",
    "description": "すべての銅ブロックに磨く加工をしその後磨きを除去する!!!",
    "detail": "銅ブロック、風化した銅、錆びた銅、酸化した銅を全てを錆止めし、その後錆止めを落とす？",
    "gold": "30",
  },{
    "id": "achive114",
    "icon": {"x": 0, "y": 0},
    "thumnail": {"x": 0, "y": 19},
    "title": "友情の癒しの力!",
    "description": "ウーパールーパーとチームを組んで戦いに勝つ",
    "detail": "ウーパールーパーとチームを組み、敵モブを倒す。",
    "gold": "30",
  },{
    "id": "achive115",
    "icon": {"x": 0, "y": 0},
    "thumnail": {"x": 1, "y": 19},
    "title": "洞窟と崖",
    "description": "世界の頂点（限界高度）から世界の底へ落下し、生き残る。",
    "detail": "建築高度上限（y=320）からワールドの底へ落下し、生き残る。",
    "gold": "30",
  },{
    "id": "achive116",
    "icon": {"x": 0, "y": 0},
    "thumnail": {"x": 4, "y": 19},
    "title": "スター トレーダー",
    "description": "限界高度で村人と取引する",
    "detail": "建築高度上限（y=320）で村人との取引をする。",
    "gold": "20",
  },{
    "id": "achive117",
    "icon": {"x": 0, "y": 0},
    "thumnail": {"x": 3, "y": 19},
    "title": "サウンド オブ ミュージック",
    "description": "ジュークボックスの音楽で牧草地を盛り上げる。",
    "detail": "草原バイオームに居る状態で、ジュークボックスでレコードを使用する。",
    "gold": "10",
  },{
    "id": "achive118",
    "icon": {"x": 0, "y": 0},
    "thumnail": {"x": 2, "y": 19},
    "title": "アットホームな感じ",
    "description": "オーバーワールドのマグマ溜まりでストライダーを長く乗りこなす。",
    "detail": "ストライダーに騎乗し、溶岩の上を50ブロック歩く。",
    "gold": "20",
  },{
    "id": "achive119",
    "icon": {"x": 0, "y": 0},
    "thumnail": {"x": 0, "y": 20},
    "title": "拡散",
    "description": "カタリストの隣のモブを倒す.",
    "detail": "スカルクカタリストの近くで、動物の子供・アレイ・コウモリ・アイアン ゴーレム・スノー ゴーレム・オタマジャクシ・村人・行商人以外の生物を倒す。",
    "gold": "10",
  },{
    "id": "achive120",
    "icon": {"x": 0, "y": 0},
    "thumnail": {"x": 5, "y": 19},
    "title": "お誕生日の歌",
    "description": "アレイが音符ブロックにケーキを落とすようにさせる",
    "detail": "アイテムのケーキがドロップされている間に、アレイにケーキを与えて飼いならしてから、その近くで音符ブロックを鳴らす。",
    "gold": "10",
  },{
    "id": "achive121",
    "icon": {"x": 0, "y": 0},
    "thumnail": {"x": 2, "y": 20},
    "title": "力を合わせて!",
    "description": "持ち物に３つのフロッグライトをすべてそろえる",
    "detail": "真珠色のフロッグライト、新緑色のフロッグライト、黄土色のフロッグライトを、それぞれ1つずつインベントリに入っている必要がある。",
    "gold": "30",
  },{
    "id": "achive122",
    "icon": {"x": 0, "y": 0},
    "thumnail": {"x": 1, "y": 20},
    "title": "スニーク 100",
    "description": "スカルクセンサーを起動せずに横に忍び寄る",
    "detail": "スカルクセンサー、またはウォーデンの近くでスニークしながら歩き、それらを反応させたり怒らせたりしないようにする。",
    "gold": "10",
  },{
    "id": "achive123",
    "icon": {"x": 0, "y": 0},
    "thumnail": {"x": 3, "y": 20},
    "title": "Planting the past",
    "description": "Plant any Sniffer seed",
    "detail": "—",
    "gold": "10",
  },{
    "id": "achive124",
    "icon": {"x": 0, "y": 0},
    "thumnail": {"x": 4, "y": 20},
    "title": "Careful restoration",
    "description": "Make a Decorated Pot out of 4 Pottery Shards",
    "detail": "—",
    "gold": "10",
  },{
    "id": "achive125",
    "icon": {"x": 0, "y": 0},
    "thumnail": {"x": 5, "y": 20},
    "title": "Smithing with style",
    "description": "Apply these smithing templates at least once: Spire, Snout, Rib, Ward, Silence, Vex, Tide, Wayfinder",
    "detail": "—",
    "gold": "30",
  }
];


